apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - name: "db-svc"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-db