apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: vote
spec:
  type: clusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis