apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: res
  name: res
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: res
  template:
    metadata:
      labels:
        app: res
    spec:
      containers:
      - image: dockersamples/examplevotingapp_result:before
        name: res
        ports:
        - containerPort: 80
          name: res